### ISSUE TITLE
Make proceeding to next comic when current one is finished optional

### ISSUE THREAD

**Issue by ToxicFrog** [ajslater/codex#149]
In general I like a clear break between comics, even when it's right about what the "next comic" should be (which it isn't always).

**Comment by ajslater** [comment]
My thinking on this is that I will probably provide a visual cue that you're about to change books, rather than an option to disable the behavior.
I'm holding off on implementation because:

-  I'm still pondering what sort of cue. I first thought of changing the mouse cursor, but that seems too subtle. I also don't really want to obscure much of the page. I might obscure the page a little if changing comics took two next presses or clicks.
- I'm holding off on changing the reader much until Vuetify 3, my frontend toolkit, releases later this year.

**Comment by ToxicFrog** [comment]
The approach I took when hacking on Ubooquity was that when you reach the start/end of a book, the next/previous page buttons (whether you're using the mouse or the keyboard) will cause the corresponding edge of the screen to flash red for ~1s; in order to actually navigate out of the book you have to double-press/click (with a 1s timeout, i.e. while the red glow is still there). This makes it really obvious you're at the end and makes it hard to do by accident, but easy to do on purpose using the same UI gestures you're already accustomed to.

**Comment by ajslater** [comment]
With v0.10.5 there is additional UI in the reader to make the user aware that books are about to be changed.
