### ISSUE TITLE
xapian errors during first run

### ISSUE THREAD

**Issue by beville** [ajslater/codex#171]
On the first run with no config folder, I see some stack traces of xapian related errors:

`xapian.DatabaseOpeningError: Couldn't detect type of database`

and 

`xapian_backend.InvalidIndexError: Unable to open index at /opt/codex/config/xapian_index`

I've been seeing this since I first started playing with Codex, but was assuming it was because something in my environment was screwed up, since I just installed Codex as root with pip.  

I was hitting some dependency issues on my server, so finally figured out (I think) how to run with venv.  I'm still seeing the same message on the first run.  Is this expected and ignore-able?

Attaching the output from the execution
[codex_first_run.txt](https://github.com/ajslater/codex/files/8799964/codex_first_run.txt)

(This is on Ubuntu 20.04.4 LTS)

**Comment by ajslater** [comment]
This was caused by the 'janitor' thread noticing upon first startup that it hadn't run in more than 24 hours and kicking off a search engine index update _before_ the search index had been created.

Search engine updates now check that the search index exists and is matched with the current database before updating and if they're not, create the index instead.
