### ISSUE TITLE
Progress Bars Deysynchronizing

### ISSUE THREAD

**Issue by ajslater** [ajslater/codex#213]
@ToxicFrog reports progress bars not reflecting read state accurately.

> E.g. A Series has four volumes, all four are marked read, but the progress bar for the containing folder is stuck at 50%.

If this was a caching issue I may have solved this with version `v1.0.0`. If it really is a progress calculation issue and the bug persists I'll have to look into it.

**Comment by ToxicFrog** [comment]
This is still happening in 1.1.4; I updated from 0.14.4 and it lost most of my progress information, but when I go to reconstruct it by marking folders read, the folder goes to 50% read instead of 100% even though all the items in it are marked read. It's like it thinks each folder has twice as many issues in it as it actually has.

**Comment by ToxicFrog** [comment]
It is not happening with everything; I think only previously affected folders are still exhibiting this behaviour. Ones I haven't interacted with before are fine. Since I've lost all my progress tracking anyways, I wonder if a full database rebuild would fix it?

**Comment by ajslater** [comment]
I'm having trouble replicating this, but it's good to know it occurs in folder mode. I'll keep looking.

**Comment by ajslater** [comment]
I think this was fixed in v1.3.6

**Comment by ToxicFrog** [comment]
It does indeed appear to be fixed! Huzzah!
