### ISSUE TITLE
[Bug] Page has a vertical scroll bar in reader mode.

### ISSUE THREAD

**Issue by bmfrosty** [ajslater/codex#255]
Tried this in both Chrome and Brave.  Reader mode gets a vertical scroll bar.  Nothing large enough to cut off anything but margin though. 

Lowest priority.

**Comment by ajslater** [comment]
Fixed!
All the various ways to lay out the page are much easier using `display: inline` images, however the helpful browser then treats the image like text and adds a little padding. `display: block` fixes this issue but then layout for two pages becomes very difficult.
So this can be fixed by adding `font-size: 0` to a containing element and poof, no padding. There's no text in these pages anyway so that works.
