### ISSUE TITLE
OPDS "Newest Issues" going by publish date and not added time

### ISSUE THREAD

**Issue by beville** [ajslater/codex#262]
Not sure if this is a bug or if it's by design, but I noticed that with the OPDS "Newest Issues" list (when I get it to load) the first item that shows is the one with the latest publish date.  This became pretty clear when I had some fake test comics that have future publish dates.  If I add another "real" comic to the library folder it shows up in the web UI where I have the view as Issues sorted by "Added Date", order descending.  It doesn't appear in the OPDS "Newest Issues" view.

Peeking at the XML feed, I see that for "Newest Issues" is has "`?orderBy=date&orderReverse=True`"

Maybe it should be something like "`?orderBy=updated_at&orderReverse=True`"? (or maybe `created_at`?)

**Comment by ajslater** [comment]
This is by design, but I think there's a good argument that it's not the correct design.

Personally, I'm usually interested in publish dates. 
But I find talking to people in discord that they are much more interested in the acquisition date. So I think i may rename it to "Recently Added' and use , `created_at` for the sort.

**Comment by ajslater** [comment]
Changed to "Recently Added"  `?created_at&orderReverse=True` in v1.2.8
