### ISSUE TITLE
Docker image not working on arm v7 (Pi4B+)

### ISSUE THREAD

**Issue by Drudoo** [ajslater/codex#312]
Pulling the image on arm v7 (Pi 4B+) will result in: 

    ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

**Comment by ajslater** [comment]
Yes, Codex is not currently built for arm32 on docker.
This has been due to some upstream problems, that cause the arm32 build to
take too long on the free tier on my free build platform.
But it's been a while, and much has changed. So i might give this another
shot. Thanks for pinging me on this. I'll update this ticket if and when I
try adding arm32 back into the supported docker images.
