### ISSUE TITLE
[Feature Request] Ability to exclude "Remove Covers" from nightly maintenance.

### ISSUE THREAD

**Issue by tehguitarist** [ajslater/codex#319]
The title says it all really. Seems like covers are being deleted every night, necessitating the need to rebuild them every time.

If there's a reason for this, all good! Just figured it would save one repeating task. That said, if the task that's actually running is "Remove Orphan Covers" then please ignore me.

**Comment by ajslater** [comment]
The nightly cover remover is only supposed to remove covers from comics that no longer exist in the database. For instance on a night where I removed no comics during the day, my logs look like this:
```
2023-06-06 00:00:00 PDT DEBUG   Removing 0 possible cover thumbnails...
2023-06-06 00:00:00 PDT DEBUG   Remove Covers: 0/0
2023-06-06 00:00:00 PDT INFO    Removed 0 cover thumbnails.
2023-06-06 00:00:00 PDT INFO    Removed 0 covers for missing comics.
2023-06-06 00:00:01 PDT INFO    Waiting 23 hours until next maintenance.
```
Do your logs look different?

Covers are generated when the browser looks for them, so you will only have covers for comics you've looked at with the browser. For instance, I have 143 covers for for a bout 900 comics, because I usually browse with the "UNREAD" fllter on.
e.g.
```sh
codex$ find config/cache/covers -name "*.webp" | wc
     143     143    5291
```

**Comment by tehguitarist** [comment]
That clears things up. I saw a task of "Removing Covers" and misunderstood. Apologies for bothering you!
