### ISSUE TITLE
Search by Issue Number Fails

### ISSUE THREAD

**Issue by beville** [ajslater/codex#356]
Searching by issue number doesn't ever seem to work

`series:'Walking Dead' issue:2`
`series:'Walking Dead' number:2`
`series:'Walking Dead' issue_number:2`
`series:'Walking Dead' 2`

**Comment by ajslater** [comment]
This should be fixed in [v1.5.8](https://github.com/ajslater/codex/releases/tag/v1.5.8)
The fix was a little larger than just this bug.
There is a new search field `issue` which is a string comprised of `issue_number` + `issue_suffix`
`issue_number` is now a working searchable variable precision float instead of a difficult to use fixed precision decimal.
so is `community_rating` and `critical_rating`.

A search index rebuild will be required to index these correctly.

Thanks for reporting this. I feel better that this is less crummy.
