### ISSUE TITLE
OPDS reading issue. Cover only

### ISSUE THREAD

**Issue by abillauer** [ajslater/codex#403]
Using codex v1.6.7 with chunky reader. 

When using OPDS to read a book the book opens fine but only shows the cover. 
The logs do not show the usual meta-data gathering codex does on a read with the web browser.

If I read the comic in the web browser first and trigger the meta-data gathering then I can see entire book via OPDS.

Import Metadata on Library Scan is disables and Folder View is enabled.

**Comment by ajslater** [comment]
fixed in [v1.6.8](https://github.com/ajslater/codex/releases/tag/v1.6.8)

I'm not even sure how this broke. I had a fix for Chunky streaming in the code already and I could swear nothing related to it changed. Regardless, I rewrote it to be a little less hacky and slightly faster and it seems to work now.

**Comment by abillauer** [comment]
Thanks. Confirmed it works.
