### ISSUE TITLE
iPad - incorrect up arrow behavior

### ISSUE THREAD

**Issue by AustinHasten** [ajslater/codex#408]
On iPad, using the up arrow in the browser takes me to the root, rather than going up one level. This happens in all browser modes (folder, publisher, etc). This occurs both when requesting mobile and desktop sites in Safari. This also occurs in the Stadium browser app. This does not occur on my desktop. Codex 1.6.9.

See below video where I go down two levels, the press the up arrow and get taken back to the root.

https://github.com/user-attachments/assets/2306354d-dc6b-41f7-ae1d-b16a4c19bbec

**Comment by abillauer** [comment]
As far as "clicking the Up arrow takes you all the way up to the root folder every time rather than going up a single level " goes, I though that was desired behavior. If you want to go up one level I click on the path name. If you click on the arrow it takes you to the root.

That behavior is consistent on the ipad and on the desktop. As far as I am concerned, that should stay that way.

**Comment by ajslater** [comment]
abillauer is correct This is a design decision, for better or worse. 
The behavior before v1..6.0 was that the up arrow with top line would go to the top and the up arrow without a top line would go up one level.
With v1.6.0, the up arrow has gone away. Now we only have the top arrow with top line and breadcrumbs.
This means you can visually see where in the tree you are, but instead of a well known button to go up a level you have to hunt and find the end of the breadcrumbs.
I do miss the simple muscle memory of "up one level is always here", but I also had some demand for breadcrumbs to show position.

**Comment by AustinHasten** [comment]
Thanks for clarifying. I must have accidentally been clicking on the breadcrumbs while on desktop, leading me to believe the behavior was different.
